services:
  - type: web
    name: wealthtracker
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate && cd ../client && npm install && npm run build && cp -r build ../server/public
    startCommand: npx prisma migrate deploy && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: PORT
        value: 5000
